/**
 * Skill Creator
 *
 * Phase 2 of the self-improving loop.
 * Creates reusable skills from repeated patterns or complex tasks.
 */

import * as fs from 'fs';
import { existsSync, mkdirSync } from 'fs';
import * as path from 'path';

import type { SkillTemplate } from './types';

export class SkillCreator {
  private skillsDir: string;
  private memoryDir: string;
  private threshold: number;

  constructor(skillsDir: string, memoryDir: string, threshold: number = 5) {
    this.skillsDir = skillsDir;
    this.memoryDir = memoryDir;
    this.threshold = threshold;
  }

  /**
   * Analyze task history and create skills for recurring patterns
   */
  async createSkills(complexTasks: SkillTemplate[]): Promise<SkillTemplate[]> {
    const created: SkillTemplate[] = [];

    // Filter by threshold
    const eligible = complexTasks.filter((t) => t.frequency >= this.threshold || t.complexity >= 7);

    for (const template of eligible) {
      const skillPath = path.join(this.skillsDir, template.name);

      if (existsSync(skillPath)) {
        // Update existing skill
        this.updateExistingSkill(skillPath, template);
      } else {
        // Create new skill
        this.createNewSkill(template);
        created.push(template);
      }
    }

    return created;
  }

  /**
   * Create a new skill from template
   */
  private createNewSkill(template: SkillTemplate): void {
    const skillPath = path.join(this.skillsDir, template.name);

    if (!existsSync(skillPath)) {
      mkdirSync(skillPath, { recursive: true });
    }

    // Create SKILL.md
    const skillContent = this.buildSkillMd(template);
    fs.writeFileSync(path.join(skillPath, 'SKILL.md'), skillContent, 'utf8');

    // Create references directory if needed
    mkdirSync(path.join(skillPath, 'references'), { recursive: true });

    // Create scripts directory
    mkdirSync(path.join(skillPath, 'scripts'), { recursive: true });
  }

  /**
   * Update an existing skill
   */
  private updateExistingSkill(skillPath: string, template: SkillTemplate): void {
    const skillMdPath = path.join(skillPath, 'SKILL.md');

    if (existsSync(skillMdPath)) {
      const existing = fs.readFileSync(skillMdPath, 'utf8');
      // Append new usage examples if different
      if (!existing.includes(template.description)) {
        const updated = existing.replace(
          /(#+\s*Usage\s*\n)([\s\S]*?)(?=\n#|$)/,
          (_, header, existingUsage) => {
            return `${header}${existingUsage}\n- [${new Date().toISOString().slice(0, 10)}] ${template.description} (from ${template.sourceSessions.length} sessions)\n`;
          },
        );
        fs.writeFileSync(skillMdPath, updated, 'utf8');
      }
    }
  }

  /**
   * Build SKILL.md content from template
   */
  private buildSkillMd(template: SkillTemplate): string {
    const now = new Date().toISOString().slice(0, 10);

    return `# ${template.name}

<!--
Auto-generated by Argentum Self-Improving Loop
Created: ${now}
Source sessions: ${template.sourceSessions.length}
Frequency: ${template.frequency}
Complexity: ${template.complexity}/10
-->

## Description

${template.description}

## Triggers

${template.triggers.map((t) => `- ${t}`).join('\n')}

## Usage

<!-- Add usage examples as discovered -->

## Notes

- Auto-generated skill - review and refine as needed
- Last updated: ${now}

---

*Generated by Argentum self-improving loop*
`;
  }

  /**
   * Detect common task patterns from session content
   */
  async detectPatterns(sessionsContent: string[]): Promise<SkillTemplate[]> {
    const templates: SkillTemplate[] = [];
    const patterns = new Map<string, { count: number; sessions: string[]; examples: string[] }>();

    for (const content of sessionsContent) {
      // Simple pattern detection based on common task keywords
      const taskPatterns = [
        {
          pattern: /write[ing]?\s+(?:a\s+)?(email|letter|message)/gi,
          name: 'email-writing',
          category: 'writing',
        },
        { pattern: /summarize[ing]?/gi, name: 'summarization', category: 'analysis' },
        {
          pattern: /debug(?:ging)?|fix(?:ing)?\s+(?:the\s+)?error/gi,
          name: 'debugging',
          category: 'coding',
        },
        { pattern: /explain[ing]?/gi, name: 'explanation', category: 'education' },
        { pattern: /research[ing]?/gi, name: 'research', category: 'analysis' },
        { pattern: /code\s+review/gi, name: 'code-review', category: 'coding' },
        {
          pattern: /write\s+(?:a\s+)?(function|class|module|script)/gi,
          name: 'code-generation',
          category: 'coding',
        },
        { pattern: /translate[ing]?/gi, name: 'translation', category: 'language' },
        { pattern: /plan[ning]?|roadmap/gi, name: 'planning', category: 'strategy' },
        { pattern: /TODO|FIXME|HACK|XXX/gi, name: 'todo-processing', category: 'coding' },
      ];

      for (const { pattern, name, category } of taskPatterns) {
        const matches = content.match(pattern);
        if (matches && matches.length > 0) {
          const existing = patterns.get(name);
          if (existing) {
            existing.count += matches.length;
            if (!existing.sessions.includes('session')) {
              existing.sessions.push('session');
            }
            if (existing.examples.length < 3) {
              existing.examples.push(content.slice(0, 100));
            }
          } else {
            patterns.set(name, {
              count: matches.length,
              sessions: ['session'],
              examples: [content.slice(0, 100)],
            });
          }
        }
      }
    }

    // Convert to templates
    for (const [name, data] of patterns.entries()) {
      if (data.count >= this.threshold) {
        templates.push({
          name: `auto-${name}`,
          description: `Pattern detected ${data.count} times across ${data.sessions.length} sessions`,
          category: this.inferCategory(name),
          triggers: this.inferTriggers(name),
          complexity: Math.min(10, Math.floor(data.count / 2)),
          frequency: data.count,
          content: '',
          sourceSessions: data.sessions,
        });
      }
    }

    return templates;
  }

  /**
   * Infer category from pattern name
   */
  private inferCategory(name: string): string {
    const categoryMap: Record<string, string> = {
      'email-writing': 'writing',
      'summarization': 'analysis',
      'debugging': 'coding',
      'explanation': 'education',
      'research': 'analysis',
      'code-review': 'coding',
      'code-generation': 'coding',
      'translation': 'language',
      'planning': 'strategy',
      'todo-processing': 'coding',
    };
    return categoryMap[name] ?? 'general';
  }

  /**
   * Infer triggers from pattern name
   */
  private inferTriggers(name: string): string[] {
    const triggersMap: Record<string, string[]> = {
      'email-writing': ['write email', 'compose message', 'draft letter'],
      'summarization': ['summarize', 'brief summary', 'TLDR'],
      'debugging': ['debug', 'fix error', 'not working'],
      'explanation': ['explain', 'how does', 'what is'],
      'research': ['research', 'find information', 'investigate'],
      'code-review': ['review code', 'check code', 'code review'],
      'code-generation': ['write code', 'generate code', 'create function'],
      'translation': ['translate', 'convert to', 'in language'],
      'planning': ['plan', 'roadmap', 'strategy'],
      'todo-processing': ['TODO', 'FIXME', 'tasks'],
    };
    return triggersMap[name] ?? [`${name.replace('-', ' ')} task`];
  }

  /**
   * Get list of auto-created skills
   */
  listAutoSkills(): string[] {
    if (!existsSync(this.skillsDir)) {
      return [];
    }

    try {
      return fs
        .readdirSync(this.skillsDir, { encoding: 'utf8' })
        .filter((f) => f.startsWith('auto-'))
        .filter((f) => fs.existsSync(path.join(this.skillsDir, f, 'SKILL.md')));
    } catch {
      return [];
    }
  }
}
