# These are supported funding model platforms

github:
  - AG064

patreon:
  - ag064

ko_fi: ag064

tidelift: "npm/ag-claw"

open_collective:

buy_me_a_coffee:
  - ag064

custom:
  - name: "Crypto (TRC20)"
    url: "your-tron-address-here"
