export const APP_VERSION = '0.0.9';

export const sections = [
  {
    id: 'onboarding',
    icon: 'spark',
    title: 'Onboarding',
    eyebrow: 'First run',
    requiresSetup: false,
  },
  { id: 'chat', icon: 'chat', title: 'Chat', eyebrow: 'Workspace', requiresSetup: false },
  { id: 'gateway', icon: 'gateway', title: 'Gateway', eyebrow: 'Runtime', requiresSetup: true },
  {
    id: 'local-server',
    icon: 'cpu',
    title: 'Local Server',
    eyebrow: 'llama.cpp',
    requiresSetup: true,
  },
  {
    id: 'security',
    icon: 'shield',
    title: 'Security & Permissions',
    eyebrow: 'Control',
    requiresSetup: false,
  },
  {
    id: 'pc-stats',
    icon: 'cpu',
    title: 'Argentum System Dashboard',
    eyebrow: 'System',
    requiresSetup: false,
  },
  {
    id: 'settings',
    icon: 'settings',
    title: 'Settings',
    eyebrow: 'Configuration',
    requiresSetup: false,
  },
  {
    id: 'diagnostics',
    icon: 'pulse',
    title: 'Diagnostics',
    eyebrow: 'Doctor',
    requiresSetup: false,
  },
  { id: 'logs', icon: 'logs', title: 'Activity Logs', eyebrow: 'Timeline', requiresSetup: true },
  {
    id: 'update',
    icon: 'download',
    title: 'Updates',
    eyebrow: 'New version',
    requiresSetup: false,
    updateAvailable: false,
  },
];

export const onboardingSteps = [
  'Welcome',
  'Workspace',
  'Choose provider',
  'Configure access',
  'Choose model',
  'Basic behavior',
  'Test and start',
];

export const fontOptions = {
  ui: [
    {
      id: 'monaspace-krypton',
      label: 'Monaspace Krypton',
      css: "'Monaspace Krypton', 'Cascadia Code', 'Segoe UI', ui-sans-serif, system-ui, sans-serif",
    },
    {
      id: 'system',
      label: 'System UI',
      css: "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    },
    {
      id: 'github',
      label: 'GitHub Sans',
      css: "'Mona Sans', 'Hubot Sans', Inter, ui-sans-serif, system-ui, sans-serif",
    },
    {
      id: 'windows',
      label: 'Segoe UI',
      css: "'Segoe UI', Inter, ui-sans-serif, system-ui, sans-serif",
    },
    {
      id: 'compact',
      label: 'Compact Sans',
      css: "'Arial', 'Helvetica Neue', ui-sans-serif, system-ui, sans-serif",
    },
  ],
  mono: [
    {
      id: 'monaspace-krypton',
      label: 'Monaspace Krypton',
      css: "'Monaspace Krypton', 'Cascadia Code', 'JetBrains Mono', ui-monospace, monospace",
    },
    {
      id: 'jetbrains',
      label: 'JetBrains Mono',
      css: "'JetBrains Mono', 'Cascadia Code', Consolas, monospace",
    },
    {
      id: 'cascadia',
      label: 'Cascadia Code',
      css: "'Cascadia Code', 'Cascadia Mono', Consolas, monospace",
    },
    {
      id: 'github-mono',
      label: 'GitHub Mono',
      css: "'Monaspace Neon', 'SFMono-Regular', Consolas, monospace",
    },
    {
      id: 'system-mono',
      label: 'System mono',
      css: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', monospace",
    },
  ],
};

export const thinkingLevels = [
  {
    id: 'fast',
    label: 'Fast',
    effort: 'low',
    detail: 'Shorter replies, lower latency, lighter reasoning.',
  },
  {
    id: 'balanced',
    label: 'Balanced',
    effort: 'medium',
    detail: 'Good default for everyday planning, chat, and implementation.',
  },
  {
    id: 'deep',
    label: 'Deep',
    effort: 'high',
    detail: 'More careful reasoning for ambiguous, risky, or multi-step work.',
  },
];

export const contextAccessOptions = [
  {
    id: 'workspace-summary',
    label: 'Workspace summary',
    status: 'Recommended',
    detail:
      'Argentum may see the selected workspace path, config health, gateway state, and high-level project status.',
  },
  {
    id: 'profile',
    label: 'Profile details',
    status: 'Personal',
    detail:
      'Argentum may use your name, the agent name, and the system prompt you write during setup.',
  },
  {
    id: 'logs',
    label: 'Logs and diagnostics',
    status: 'Review first',
    detail:
      'Argentum may summarize redacted gateway logs, diagnostics, and audit status. Secrets stay hidden.',
  },
  {
    id: 'tool-state',
    label: 'Tool and permission state',
    status: 'Security',
    detail:
      'Argentum may see which local capabilities are allowed, blocked, or waiting for approval.',
  },
  {
    id: 'system-dashboard',
    label: 'Live system dashboard',
    status: 'Optional',
    detail:
      'Argentum may collect local CPU, memory, process, disk, network, temperature, and GPU telemetry while the dashboard tab is open.',
  },
  {
    id: 'local-server',
    label: 'Local llama.cpp server',
    status: 'Optional',
    detail:
      'Argentum may see and control the bundled or workspace-provided llama.cpp server process, endpoint, model path, and redacted logs.',
  },
];

export const modelMetadata = {
  'gpt-5.5': {
    maxContextTokens: 272000,
    contextWindow: '272k tokens',
    maxContextWindow: '272k tokens',
    currentContextLabel: 'Codex catalog: large workspace context',
    capabilities: ['frontier reasoning', 'coding', 'research', 'tools', 'vision'],
    detail: 'Frontier Codex model for complex coding, research, and real-world work.',
  },
  'gpt-5.5-pro': {
    maxContextTokens: 272000,
    contextWindow: 'Plan/account dependent',
    maxContextWindow: 'Plan/account dependent',
    currentContextLabel: 'Confirm availability with provider test',
    capabilities: ['frontier reasoning', 'long tasks', 'tools'],
    detail:
      'High-end OpenAI option. Availability and limits depend on the selected authorization method.',
  },
  'gpt-5.4': {
    maxContextTokens: 272000,
    contextWindow: '272k tokens',
    maxContextWindow: '1M tokens when available',
    currentContextLabel: 'Codex catalog: expandable large context',
    capabilities: ['coding', 'reasoning', 'tools', 'vision'],
    detail: 'Strong model for everyday coding and agent work.',
  },
  'gpt-5.4-pro': {
    maxContextTokens: 272000,
    contextWindow: 'Plan/account dependent',
    maxContextWindow: 'Plan/account dependent',
    currentContextLabel: 'Confirm availability with provider test',
    capabilities: ['reasoning', 'coding', 'analysis'],
    detail: 'Higher-capability GPT-5.4 profile when exposed by the selected provider.',
  },
  'gpt-5.4-mini': {
    maxContextTokens: 272000,
    contextWindow: '272k tokens',
    maxContextWindow: '272k tokens',
    currentContextLabel: 'Codex catalog: fast large context',
    capabilities: ['fast coding', 'tools', 'vision'],
    detail: 'Small, fast, cost-efficient model for simpler coding and setup tasks.',
  },
  'gpt-5.4-nano': {
    maxContextTokens: 128000,
    contextWindow: 'Provider dependent',
    maxContextWindow: 'Provider dependent',
    currentContextLabel: 'Best for short tasks',
    capabilities: ['fast chat', 'low cost'],
    detail: 'Lightweight option for quick replies when exposed by the provider.',
  },
  'gpt-5-mini': {
    maxContextTokens: 128000,
    contextWindow: 'Provider dependent',
    maxContextWindow: 'Provider dependent',
    currentContextLabel: 'Best for short tasks',
    capabilities: ['fast chat', 'low cost'],
    detail: 'Compact GPT-5 profile for simple chat and routing.',
  },
  'gpt-5-nano': {
    maxContextTokens: 64000,
    contextWindow: 'Provider dependent',
    maxContextWindow: 'Provider dependent',
    currentContextLabel: 'Best for tiny tasks',
    capabilities: ['very fast chat', 'classification'],
    detail: 'Smallest GPT-5-style profile when exposed by the provider.',
  },
  'gpt5': {
    maxContextTokens: 128000,
    contextWindow: 'Provider alias',
    maxContextWindow: 'Provider alias',
    currentContextLabel: 'Alias depends on endpoint',
    capabilities: ['general chat'],
    detail: 'Provider alias. Argentum tests the endpoint to confirm what it maps to.',
  },
  'gpt-4.1': {
    maxContextTokens: 128000,
    contextWindow: 'Provider dependent',
    maxContextWindow: 'Provider dependent',
    currentContextLabel: 'Stable general-purpose context',
    capabilities: ['general chat', 'coding', 'analysis'],
    detail: 'Stable general-purpose model option for API-key based chat.',
  },
  'gpt-5.3-codex': {
    maxContextTokens: 272000,
    contextWindow: '272k tokens',
    maxContextWindow: '272k tokens',
    currentContextLabel: 'Codex catalog: coding optimized',
    capabilities: ['coding', 'tools', 'vision'],
    detail: 'Coding-optimized Codex model.',
  },
  'gpt-5.2': {
    maxContextTokens: 272000,
    contextWindow: '272k tokens',
    maxContextWindow: '272k tokens',
    currentContextLabel: 'Codex catalog: long-running agents',
    capabilities: ['long tasks', 'coding', 'tools', 'vision'],
    detail: 'Optimized for professional work and long-running agents.',
  },
  'MiniMax-M2.7': {
    maxContextTokens: 200000,
    contextWindow: '200k practical target',
    maxContextWindow: 'Provider controlled',
    currentContextLabel: 'MiniMax Token Plan: M2.7 requests reset on a rolling 5-hour window.',
    capabilities: [
      'agentic coding',
      'tool use',
      'vision',
      'long task state tracking',
      'multimodal token plan',
    ],
    detail:
      'MiniMax M2.7 works best with clear intent, concrete examples, phased long tasks, and state tracking.',
  },
  'MiniMax-M2.7-highspeed': {
    maxContextTokens: 200000,
    contextWindow: '200k practical target',
    maxContextWindow: 'Plan dependent',
    currentContextLabel: 'MiniMax Token Plan high-speed tier, when available for the selected key.',
    capabilities: ['faster M2.7 routing', 'agentic coding', 'tool use', 'vision'],
    detail: 'High-speed MiniMax M2.7 profile. Argentum verifies availability with Test Provider.',
  },
  'MiniMax-Text-01': {
    maxContextTokens: 128000,
    contextWindow: 'Provider dependent',
    maxContextWindow: 'Provider dependent',
    currentContextLabel: 'Legacy MiniMax text endpoint. Prefer M2.7 when Token Plan is active.',
    capabilities: ['chat', 'text generation'],
    detail: 'MiniMax text model kept as a testing model until the provider test confirms support.',
  },
  'claude-sonnet-4-20250514': {
    maxContextTokens: 200000,
    contextWindow: '200k tokens',
    maxContextWindow: '200k tokens',
    currentContextLabel: 'Anthropic API: extended thinking, tool use, vision.',
    capabilities: ['frontier reasoning', 'coding', 'analysis', 'tools', 'vision'],
    detail:
      'Claude Sonnet 4 supports extended thinking. Argentum maps fast, balanced, and deep to manual token budgets of 1024, 8000, and 24000 tokens.',
  },
  'claude-opus-4-20250514': {
    maxContextTokens: 200000,
    contextWindow: '200k tokens',
    maxContextWindow: '200k tokens',
    currentContextLabel: 'Anthropic API: strongest reasoning, extended thinking, tool use.',
    capabilities: ['frontier reasoning', 'coding', 'research', 'analysis', 'tools', 'vision'],
    detail:
      'Claude Opus 4 uses manual extended-thinking budgets: 1024 (fast), 8000 (balanced), and 24000 (deep). Best for complex multi-step tasks.',
  },
  'lmstudio-auto': {
    maxContextTokens: 32768,
    contextWindow: 'Endpoint reported when available',
    maxContextWindow: 'Model dependent',
    currentContextLabel:
      'Local endpoint. Argentum checks LM Studio /v1/models or REST model metadata when available.',
    capabilities: ['local chat', 'tools when model/server supports them'],
    detail:
      'Use the model currently loaded by LM Studio. API key can stay blank for local endpoints unless you configured one.',
  },
  'qwen/qwen2.5-0.5b-instruct': {
    maxContextTokens: 32768,
    contextWindow: 'Model dependent',
    maxContextWindow: 'Model dependent',
    currentContextLabel:
      'Tiny local Qwen profile. Confirm the loaded context through the local endpoint.',
    capabilities: ['local chat', 'tools when enabled'],
    detail: 'Very small Qwen2.5 instruction model for CPU-only or low-memory machines.',
  },
  'qwen/qwen3-0.6b': {
    maxContextTokens: 32768,
    contextWindow: 'Model dependent',
    maxContextWindow: 'Model dependent',
    currentContextLabel:
      'Tiny local Qwen3 profile. Confirm the loaded context through the local endpoint.',
    capabilities: ['local chat', 'reasoning', 'tools when enabled'],
    detail: '0.6B Qwen3 GGUF option for low-resource local inference.',
  },
  'qwen/qwen3.5-0.8b-instruct-ft': {
    maxContextTokens: 32768,
    contextWindow: 'Model dependent',
    maxContextWindow: 'Model dependent',
    currentContextLabel:
      'Community 0.8B local profile. Confirm actual support through endpoint test.',
    capabilities: ['local chat'],
    detail: 'Community 0.8B Qwen-family GGUF option for very small local setups.',
  },
  'google/gemma-3-1b-it': {
    maxContextTokens: 32768,
    contextWindow: 'Model dependent',
    maxContextWindow: 'Model dependent',
    currentContextLabel: 'Gemma 1B local profile. Confirm actual context through endpoint test.',
    capabilities: ['local chat'],
    detail: 'Compact Gemma 3 instruction model for lightweight local chat.',
  },
  'tinyllama/tinyllama-1.1b-chat': {
    maxContextTokens: 4096,
    contextWindow: 'Model dependent',
    maxContextWindow: 'Model dependent',
    currentContextLabel:
      'TinyLlama local profile. Context depends on quantization and server flags.',
    capabilities: ['local chat'],
    detail: 'Classic 1.1B lightweight chat model for older or CPU-only machines.',
  },
  'liquidai/lfm2.5-1.2b-instruct': {
    maxContextTokens: 32768,
    contextWindow: 'Model dependent',
    maxContextWindow: 'Model dependent',
    currentContextLabel: 'LFM 1.2B local profile. Confirm actual context through endpoint test.',
    capabilities: ['local chat'],
    detail: 'Small LiquidAI instruction model for local chat with modest hardware.',
  },
  'huggingfacetb/smollm2-360m-instruct': {
    maxContextTokens: 8192,
    contextWindow: 'Model dependent',
    maxContextWindow: 'Model dependent',
    currentContextLabel: 'Ultra-small SmolLM2 profile for minimum-resource devices.',
    capabilities: ['local chat'],
    detail: 'Ultra-small fallback when even 1B-class models are too heavy.',
  },
  'qwen/qwen3-1.7b': {
    maxContextTokens: 32768,
    contextWindow: 'Model dependent',
    maxContextWindow: 'Model dependent',
    currentContextLabel: 'Small Qwen3 profile. Confirm actual context through endpoint test.',
    capabilities: ['local chat', 'reasoning', 'tools when enabled'],
    detail: 'Stronger small local reasoning option when RAM allows 1.7B-class models.',
  },
  'openai/gpt-oss-20b': {
    maxContextTokens: 131000,
    contextWindow: 'Model dependent',
    maxContextWindow: 'Model dependent',
    currentContextLabel: 'Local GPT-OSS profile. Confirm loaded model context through LM Studio.',
    capabilities: ['local chat', 'reasoning', 'tools when enabled'],
    detail: 'Common LM Studio local model. Best limits depend on quantization and hardware.',
  },
  'google/gemma-3-27b-it': {
    maxContextTokens: 128000,
    contextWindow: 'Model dependent',
    maxContextWindow: 'Model dependent',
    currentContextLabel: 'Gemma local profile. Confirm actual context through endpoint test.',
    capabilities: ['local chat', 'vision on VLM variants'],
    detail: 'Gemma family option for local or OpenAI-compatible routes.',
  },
  'google/gemma-3-12b-it': {
    maxContextTokens: 128000,
    contextWindow: 'Model dependent',
    maxContextWindow: 'Model dependent',
    currentContextLabel: 'Gemma local profile. Confirm actual context through endpoint test.',
    capabilities: ['local chat', 'vision on VLM variants'],
    detail: 'Smaller Gemma family option for local or OpenAI-compatible routes.',
  },
  'qwen/qwen3-14b': {
    maxContextTokens: 128000,
    contextWindow: 'Model dependent',
    maxContextWindow: 'Model dependent',
    currentContextLabel: 'Qwen local profile. Confirm actual context through endpoint test.',
    capabilities: ['local chat', 'reasoning', 'tools when enabled'],
    detail: 'Qwen family option for local reasoning and coding tasks.',
  },
  'qwen/qwen2.5-vl-7b-instruct': {
    maxContextTokens: 128000,
    contextWindow: 'Model dependent',
    maxContextWindow: 'Model dependent',
    currentContextLabel:
      'Qwen VL local profile. Confirm actual context and image support through endpoint test.',
    capabilities: ['local chat', 'vision', 'tools when enabled'],
    detail:
      'Vision-capable Qwen family option when loaded in LM Studio or a compatible local server.',
  },
  'qwen2.5-coder-32b-instruct': {
    maxContextTokens: 128000,
    contextWindow: 'Model dependent',
    maxContextWindow: 'Model dependent',
    currentContextLabel: 'Qwen Coder local profile. Confirm actual context through endpoint test.',
    capabilities: ['local coding', 'tools when enabled'],
    detail: 'Common local coding model option.',
  },
  'deepseek-r1-distill-qwen-14b': {
    maxContextTokens: 128000,
    contextWindow: 'Model dependent',
    maxContextWindow: 'Model dependent',
    currentContextLabel:
      'DeepSeek reasoning profile. Confirm actual context through endpoint test.',
    capabilities: ['local chat', 'reasoning'],
    detail:
      'Reasoning-oriented local model option. Reasoning output may appear in separated blocks.',
  },
  'deepseek-coder-v2-lite-instruct': {
    maxContextTokens: 128000,
    contextWindow: 'Model dependent',
    maxContextWindow: 'Model dependent',
    currentContextLabel:
      'DeepSeek Coder local profile. Confirm actual context through endpoint test.',
    capabilities: ['local coding', 'tools when enabled'],
    detail: 'Compact DeepSeek coding model commonly used through local OpenAI-compatible servers.',
  },
  'meta-llama-3.1-8b-instruct': {
    maxContextTokens: 128000,
    contextWindow: 'Model dependent',
    maxContextWindow: 'Model dependent',
    currentContextLabel: 'Llama local profile. Confirm actual context through endpoint test.',
    capabilities: ['local chat', 'tools when enabled'],
    detail: 'General local instruction model option.',
  },
  'mistral-nemo-instruct-2407': {
    maxContextTokens: 128000,
    contextWindow: 'Model dependent',
    maxContextWindow: 'Model dependent',
    currentContextLabel: 'Mistral local profile. Confirm actual context through endpoint test.',
    capabilities: ['local chat'],
    detail: 'Compact general-purpose local model option.',
  },
  'llava-v1.6-mistral-7b': {
    maxContextTokens: 32000,
    contextWindow: 'Model dependent',
    maxContextWindow: 'Model dependent',
    currentContextLabel:
      'LLaVA local vision profile. Confirm actual image support through endpoint test.',
    capabilities: ['local chat', 'vision'],
    detail: 'Common local vision model option for image analysis through compatible servers.',
  },
  'phi-4-mini-instruct': {
    maxContextTokens: 128000,
    contextWindow: 'Model dependent',
    maxContextWindow: 'Model dependent',
    currentContextLabel: 'Phi local profile. Confirm actual context through endpoint test.',
    capabilities: ['local chat', 'tools when enabled'],
    detail: 'Compact local instruction model option for lower VRAM systems.',
  },
  'custom-local-model': {
    maxContextTokens: 32000,
    contextWindow: 'Custom / endpoint reported',
    maxContextWindow: 'Custom / endpoint reported',
    currentContextLabel:
      'Custom model ID. Test provider to confirm context, tools, vision, and reasoning support.',
    capabilities: ['custom'],
    detail: 'Enter the exact model ID exposed by your local server or provider endpoint.',
  },
};

export const experienceLevels = [
  {
    id: 'beginner',
    label: 'Beginner',
    headline: 'Explain each choice',
    detail: 'Argentum will use plain language, examples, and safer defaults while you set it up.',
  },
  {
    id: 'comfortable',
    label: 'Intermediate',
    headline: 'Balanced guidance',
    detail: 'You get the important tradeoffs without every setting slowing you down.',
  },
  {
    id: 'expert',
    label: 'Expert',
    headline: 'Show the controls',
    detail:
      'Argentum keeps the explanations compact and puts advanced options closer to the surface.',
  },
];

export const runtimeModes = [
  {
    id: 'desktop',
    label: 'Desktop app',
    headline: 'GUI first, CLI included',
    detail:
      'Best for Windows users. You get onboarding, chat, settings, approvals, logs, and diagnostics in the app.',
    preview:
      'A native desktop workspace opens after setup. Terminal tools remain available for automation.',
    examples: [
      'Ask Argentum to read a workspace file.',
      'Approve the scoped file request.',
      'See the result, audit note, and next action in Chat.',
    ],
    demoSteps: ['Chat request', 'Permission card', 'Workspace answer'],
  },
  {
    id: 'cli',
    label: 'CLI tools',
    headline: 'Terminal-first workflow',
    detail: 'Best for Linux users, scripts, and people who prefer command-line control.',
    preview:
      'The app keeps the same setup values, but daily work happens through argentum commands.',
    examples: [
      'Run argentum doctor to verify config.',
      'Use argentum gateway status before exposing a channel.',
      'Keep scripted work visible in logs.',
    ],
    demoSteps: ['Command', 'Check', 'Log'],
  },
  {
    id: 'service',
    label: 'Local service',
    headline: 'Service with desktop control',
    detail: 'Best when Argentum should expose local APIs, webchat, or integrations after approval.',
    preview: 'Services stay off until you approve them. The desktop app acts as the control room.',
    examples: [
      'Start the gateway from Chat.',
      'Approve the local network capability.',
      'Watch the service status in the terminal view.',
    ],
    demoSteps: ['Start', 'Approve', 'Serve'],
  },
];

export const providerCatalogTabs = [
  {
    id: 'stable',
    label: 'Release candidate',
    detail:
      'ChatGPT/OpenAI, MiniMax, LM Studio/local, and managed llama.cpp routes are wired for live chat and provider tests but still require release-matrix validation.',
  },
  {
    id: 'testing',
    label: 'Testing',
    detail:
      'Other providers remain selectable for testing, but they must pass Test Provider before live use.',
  },
];

export const llamaDownloadPresets = [
  {
    id: 'qwen2.5-0.5b-instruct-q4',
    modelId: 'qwen/qwen2.5-0.5b-instruct',
    label: 'Qwen2.5 0.5B Instruct',
    size: '0.5B',
    license: 'Apache-2.0',
    repo: 'Qwen/Qwen2.5-0.5B-Instruct-GGUF:Q4_K_M',
    file: 'qwen2.5-0.5b-instruct-q4_k_m.gguf',
    detail: 'Smallest default download for weak CPUs and quick smoke tests.',
  },
  {
    id: 'qwen3-0.6b-q4',
    modelId: 'qwen/qwen3-0.6b',
    label: 'Qwen3 0.6B',
    size: '0.6B',
    license: 'Apache-2.0',
    repo: 'unsloth/Qwen3-0.6B-GGUF:Q4_K_M',
    file: 'Qwen3-0.6B-Q4_K_M.gguf',
    detail: 'Tiny reasoning-capable local model for low-resource machines.',
  },
  {
    id: 'tinyllama-1.1b-chat-q4',
    modelId: 'tinyllama/tinyllama-1.1b-chat',
    label: 'TinyLlama 1.1B Chat',
    size: '1.1B',
    license: 'Apache-2.0',
    repo: 'TinyLlama/TinyLlama-1.1B-Chat-v0.2-GGUF',
    file: 'ggml-model-q4_0.gguf',
    detail: 'Classic lightweight chat model for old laptops and CPU-only tests.',
  },
  {
    id: 'smollm2-360m-instruct-q4',
    modelId: 'huggingfacetb/smollm2-360m-instruct',
    label: 'SmolLM2 360M Instruct',
    size: '0.36B',
    license: 'Apache-2.0',
    repo: 'bartowski/SmolLM2-360M-Instruct-GGUF:Q4_K_M',
    file: 'SmolLM2-360M-Instruct-Q4_K_M.gguf',
    detail: 'Ultra-small fallback for systems that cannot comfortably run 1B-class models.',
  },
  {
    id: 'qwen3-1.7b-q4',
    modelId: 'qwen/qwen3-1.7b',
    label: 'Qwen3 1.7B',
    size: '1.7B',
    license: 'Apache-2.0',
    repo: 'unsloth/Qwen3-1.7B-GGUF:Q4_K_M',
    file: 'Qwen3-1.7B-Q4_K_M.gguf',
    detail: 'Still small, but stronger than the sub-1B presets if RAM allows it.',
  },
];

export const providerPresets = [
  {
    id: 'openai',
    access: 'stable',
    label: 'ChatGPT / OpenAI',
    api: 'openai',
    apiKeyEnv: 'OPENAI_API_KEY',
    websiteUrl: 'https://platform.openai.com',
    authMethods: ['api-key', 'browser-account'],
    defaultBaseUrl: 'https://api.openai.com/v1',
    defaultModel: 'gpt-5.4-mini',
    codexDefaultModel: 'gpt-5.4-mini',
    codexModels: [
      { id: 'gpt-5.5', label: 'GPT-5.5' },
      { id: 'gpt-5.4', label: 'GPT-5.4' },
      { id: 'gpt-5.4-mini', label: 'GPT-5.4 mini' },
      { id: 'gpt-5.3-codex', label: 'GPT-5.3 Codex' },
      { id: 'gpt-5.2', label: 'GPT-5.2' },
    ],
    models: [
      { id: 'gpt-5.5', label: 'GPT-5.5' },
      { id: 'gpt-5.5-pro', label: 'GPT-5.5 pro' },
      { id: 'gpt-5.4', label: 'GPT-5.4' },
      { id: 'gpt-5.4-pro', label: 'GPT-5.4 pro' },
      { id: 'gpt-5.4-mini', label: 'GPT-5.4 mini' },
      { id: 'gpt-5.4-nano', label: 'GPT-5.4 nano' },
      { id: 'gpt-5-mini', label: 'GPT-5 mini' },
      { id: 'gpt-5-nano', label: 'GPT-5 nano' },
      { id: 'gpt5', label: 'gpt5' },
      { id: 'gpt-4.1', label: 'GPT-4.1' },
    ],
    requiresKey: true,
    detail:
      'ChatGPT browser-account authorization and OpenAI Platform API routes with strong tool and chat support.',
    highlights: [
      'Stable desktop chat route',
      'API key or Codex browser-account auth',
      'Vision/tool-capable model options',
    ],
    dataRegion: 'Varies by account, product, and provider configuration.',
    dataRoute:
      'API-key traffic goes to OpenAI Platform endpoints. Browser-account auth uses the official OpenAI/Codex authorization flow.',
    docsUrl: 'https://platform.openai.com/docs',
    termsUrl: 'https://openai.com/policies/terms-of-use',
    privacyUrl: 'https://openai.com/policies/privacy-policy',
    usageNotes:
      'Rate-limit headers are shown when OpenAI exposes them. ChatGPT/Codex account counters are shown only when the account route exposes them.',
  },
  {
    id: 'anthropic',
    access: 'testing',
    label: 'Anthropic Claude',
    api: 'anthropic',
    apiKeyEnv: 'ANTHROPIC_API_KEY',
    websiteUrl: 'https://console.anthropic.com',
    authMethods: ['api-key'],
    defaultBaseUrl: 'https://api.anthropic.com',
    defaultModel: 'claude-sonnet-4-20250514',
    models: [
      { id: 'claude-sonnet-4-20250514', label: 'Claude Sonnet 4' },
      { id: 'claude-opus-4-20250514', label: 'Claude Opus 4' },
      { id: 'claude-3-5-haiku-20241022', label: 'Claude 3.5 Haiku' },
    ],
    requiresKey: true,
    detail: 'Hosted Claude models. Good for long, careful reasoning.',
    highlights: [
      'Long-context reasoning',
      'API-key auth only in this MVP',
      'Testing route until provider test passes',
    ],
    dataRegion: 'Varies by Anthropic account and service configuration.',
    dataRoute: 'Requests go to Anthropic API endpoints configured for the selected key.',
    docsUrl: 'https://docs.anthropic.com',
    termsUrl: 'https://www.anthropic.com/legal/consumer-terms',
    privacyUrl: 'https://www.anthropic.com/legal/privacy',
    usageNotes:
      'Usage counters are unavailable unless Anthropic response headers/body expose them.',
  },
  {
    id: 'google',
    access: 'testing',
    label: 'Google Gemini',
    api: 'openai',
    apiKeyEnv: 'GOOGLE_API_KEY',
    websiteUrl: 'https://aistudio.google.com',
    authMethods: ['api-key'],
    defaultBaseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai/',
    defaultModel: 'gemini-2.5-flash',
    models: [
      { id: 'gemini-2.5-flash', label: 'Gemini 2.5 Flash' },
      { id: 'gemini-2.5-pro', label: 'Gemini 2.5 Pro' },
      { id: 'gemini-2.0-flash', label: 'Gemini 2.0 Flash' },
    ],
    requiresKey: true,
    detail: 'Gemini through the OpenAI-compatible endpoint.',
    highlights: [
      'Google AI Studio keys',
      'OpenAI-compatible route',
      'Testing route until provider test passes',
    ],
    dataRegion: 'Varies by Google account, project, and model availability.',
    dataRoute:
      'Requests go to Google Generative Language API endpoints through the configured base URL.',
    docsUrl: 'https://ai.google.dev/gemini-api/docs',
    termsUrl: 'https://ai.google.dev/gemini-api/terms',
    privacyUrl: 'https://policies.google.com/privacy',
    usageNotes:
      'Usage and quota details are shown only if Google exposes them to the API response.',
  },
  {
    id: 'openrouter',
    access: 'testing',
    label: 'OpenRouter',
    api: 'openai',
    apiKeyEnv: 'OPENROUTER_API_KEY',
    websiteUrl: 'https://openrouter.ai',
    authMethods: ['api-key'],
    defaultBaseUrl: 'https://openrouter.ai/api/v1',
    defaultModel: 'google/gemma-3-27b-it',
    models: [
      { id: 'google/gemma-3-27b-it', label: 'Google Gemma 3 27B' },
      { id: 'openai/gpt-4o-mini', label: 'OpenAI GPT-4o mini' },
      { id: 'anthropic/claude-sonnet-4', label: 'Anthropic Claude Sonnet 4' },
      { id: 'google/gemini-2.5-flash', label: 'Google Gemini 2.5 Flash' },
      { id: 'meta-llama/llama-3.3-70b-instruct', label: 'Llama 3.3 70B Instruct' },
    ],
    requiresKey: true,
    detail: 'One endpoint for many hosted model providers.',
    highlights: [
      'Multi-provider routing',
      'Provider-dependent data route',
      'Testing route until model/key are verified',
    ],
    dataRegion: 'Depends on the downstream model provider selected in OpenRouter.',
    dataRoute: 'Requests go to OpenRouter first, then to the selected downstream provider.',
    docsUrl: 'https://openrouter.ai/docs',
    termsUrl: 'https://openrouter.ai/terms',
    privacyUrl: 'https://openrouter.ai/privacy',
    usageNotes:
      'OpenRouter usage is provider/model dependent; Argentum reports only exposed counters.',
  },
  {
    id: 'nvidia',
    access: 'testing',
    label: 'NVIDIA',
    api: 'openai',
    apiKeyEnv: 'NVIDIA_API_KEY',
    websiteUrl: 'https://build.nvidia.com',
    authMethods: ['api-key'],
    defaultBaseUrl: 'https://integrate.api.nvidia.com/v1',
    defaultModel: 'deepseek-ai/deepseek-v3.2',
    models: [
      { id: 'deepseek-ai/deepseek-v3.2', label: 'DeepSeek V3.2' },
      { id: 'nvidia/llama-3.1-nemotron-70b-instruct', label: 'Llama 3.1 Nemotron 70B' },
      { id: 'meta/llama-3.1-405b-instruct', label: 'Llama 3.1 405B' },
    ],
    requiresKey: true,
    detail: 'NVIDIA-hosted OpenAI-compatible models.',
    highlights: [
      'GPU-hosted inference',
      'OpenAI-compatible API',
      'Testing route until provider test passes',
    ],
    dataRegion: 'Varies by NVIDIA deployment and account configuration.',
    dataRoute: 'Requests go to NVIDIA-hosted model endpoints for the selected model.',
    docsUrl: 'https://docs.api.nvidia.com',
    termsUrl: 'https://www.nvidia.com/en-us/about-nvidia/legal-info',
    privacyUrl: 'https://www.nvidia.com/en-us/about-nvidia/privacy-policy',
    usageNotes: 'Usage counters are shown only if NVIDIA response headers/body expose them.',
  },
  {
    id: 'groq',
    access: 'testing',
    label: 'Groq',
    api: 'openai',
    apiKeyEnv: 'GROQ_API_KEY',
    websiteUrl: 'https://console.groq.com',
    authMethods: ['api-key'],
    defaultBaseUrl: 'https://api.groq.com/openai/v1',
    defaultModel: 'meta-llama/llama-4-scout-17b-16e-instruct',
    models: [
      { id: 'meta-llama/llama-4-scout-17b-16e-instruct', label: 'Llama 4 Scout' },
      { id: 'llama-3.3-70b-versatile', label: 'Llama 3.3 70B Versatile' },
      { id: 'openai/gpt-oss-120b', label: 'GPT OSS 120B' },
      { id: 'openai/gpt-oss-20b', label: 'GPT OSS 20B' },
    ],
    requiresKey: true,
    detail: 'Fast hosted OpenAI-compatible inference.',
    highlights: [
      'Low-latency inference',
      'OpenAI-compatible API',
      'Testing route until provider test passes',
    ],
    dataRegion: 'Varies by Groq account and service configuration.',
    dataRoute: 'Requests go to Groq API endpoints for the selected model.',
    docsUrl: 'https://console.groq.com/docs',
    termsUrl: 'https://groq.com/terms-of-use',
    privacyUrl: 'https://groq.com/privacy-policy',
    usageNotes: 'Usage counters are shown only if Groq response headers/body expose them.',
  },
  {
    id: 'minimax',
    access: 'stable',
    label: 'MiniMax',
    api: 'openai',
    apiKeyEnv: 'MINIMAX_API_KEY',
    websiteUrl: 'https://platform.minimax.io',
    authMethods: ['api-key'],
    defaultBaseUrl: 'https://api.minimax.io/v1',
    defaultModel: 'MiniMax-M2.7',
    models: [
      { id: 'MiniMax-M2.7', label: 'MiniMax M2.7' },
      { id: 'MiniMax-M2.7-highspeed', label: 'MiniMax M2.7 highspeed' },
      { id: 'MiniMax-Text-01', label: 'MiniMax Text 01' },
    ],
    requiresKey: true,
    detail:
      'MiniMax hosted models through an OpenAI-style API, with Token Plan usage checks in Argentum.',
    highlights: [
      'Stable MiniMax M2.7 route',
      'Token Plan usage API',
      'Good for long practical agent tasks',
    ],
    dataRegion:
      'MiniMax account and endpoint dependent. Global platform traffic uses minimax.io endpoints; China-region service uses separate MiniMax endpoints.',
    dataRoute:
      'API-key traffic goes to the configured MiniMax API base URL. Account-page usage requires a dedicated permission-gated browser profile.',
    docsUrl: 'https://platform.minimax.io/docs',
    termsUrl: 'https://www.minimax.io/terms-of-service',
    privacyUrl: 'https://www.minimax.io/privacy-policy',
    usageNotes:
      'Official Token Plan API is the trusted source. Browser-profile account-page counters are unavailable until that integration is configured.',
    accountUsageUrl: 'https://platform.minimax.io/user-center/payment/token-plan',
  },
  {
    id: 'local',
    access: 'stable',
    label: 'LM Studio / local',
    api: 'openai',
    apiKeyEnv: 'LOCAL_LLM_API_KEY',
    websiteUrl: 'https://lmstudio.ai',
    authMethods: ['api-key'],
    defaultBaseUrl: 'http://127.0.0.1:1234/v1',
    defaultModel: 'lmstudio-auto',
    models: [
      { id: 'lmstudio-auto', label: 'LM Studio loaded model' },
      { id: 'qwen/qwen2.5-0.5b-instruct', label: 'Qwen2.5 0.5B Instruct' },
      { id: 'qwen/qwen3-0.6b', label: 'Qwen3 0.6B' },
      { id: 'qwen/qwen3.5-0.8b-instruct-ft', label: 'Qwen3.5 0.8B Instruct FT' },
      { id: 'google/gemma-3-1b-it', label: 'Gemma 3 1B IT' },
      { id: 'tinyllama/tinyllama-1.1b-chat', label: 'TinyLlama 1.1B Chat' },
      { id: 'liquidai/lfm2.5-1.2b-instruct', label: 'LFM2.5 1.2B Instruct' },
      { id: 'huggingfacetb/smollm2-360m-instruct', label: 'SmolLM2 360M Instruct' },
      { id: 'qwen/qwen3-1.7b', label: 'Qwen3 1.7B' },
      { id: 'openai/gpt-oss-20b', label: 'GPT-OSS 20B' },
      { id: 'google/gemma-3-27b-it', label: 'Gemma 3 27B IT' },
      { id: 'google/gemma-3-12b-it', label: 'Gemma 3 12B IT' },
      { id: 'qwen/qwen3-14b', label: 'Qwen3 14B' },
      { id: 'qwen/qwen2.5-vl-7b-instruct', label: 'Qwen2.5 VL 7B' },
      { id: 'qwen2.5-coder-32b-instruct', label: 'Qwen2.5 Coder 32B' },
      { id: 'deepseek-r1-distill-qwen-14b', label: 'DeepSeek R1 Distill Qwen 14B' },
      { id: 'deepseek-coder-v2-lite-instruct', label: 'DeepSeek Coder V2 Lite' },
      { id: 'meta-llama-3.1-8b-instruct', label: 'Llama 3.1 8B Instruct' },
      { id: 'mistral-nemo-instruct-2407', label: 'Mistral Nemo Instruct' },
      { id: 'llava-v1.6-mistral-7b', label: 'LLaVA 1.6 Mistral 7B' },
      { id: 'phi-4-mini-instruct', label: 'Phi 4 mini instruct' },
      { id: 'custom-local-model', label: 'Other / custom local model' },
    ],
    requiresKey: false,
    detail:
      'Stable local route for LM Studio or another OpenAI-compatible local server. Endpoint is required; API key can stay blank for local-only servers.',
    highlights: [
      'Stable local route',
      'LM Studio OpenAI-compatible API',
      'API key optional for localhost',
    ],
    dataRegion: 'Local machine unless you point the endpoint at another host.',
    dataRoute:
      'Requests go only to the endpoint you enter. Default is LM Studio on http://127.0.0.1:1234/v1.',
    docsUrl: 'https://lmstudio.ai/docs/developer',
    termsUrl: 'https://lmstudio.ai/terms',
    privacyUrl: 'https://lmstudio.ai/privacy',
    usageNotes:
      'Local usage is hardware-bound: RAM, VRAM, loaded model context, and server throughput. Argentum reports provider usage only when the local endpoint exposes it.',
    modelSearchUrl: 'https://huggingface.co/models',
  },
  {
    id: 'llama-cpp',
    access: 'stable',
    label: 'Argentum llama.cpp',
    api: 'openai',
    apiKeyEnv: 'LLAMA_CPP_API_KEY',
    websiteUrl: 'https://github.com/ggml-org/llama.cpp',
    authMethods: ['api-key'],
    defaultBaseUrl: 'http://127.0.0.1:8080/v1',
    defaultModel: 'qwen/qwen2.5-0.5b-instruct',
    models: [
      ...llamaDownloadPresets.map((preset) => ({
        id: preset.modelId,
        label: `${preset.label} GGUF`,
      })),
      { id: 'custom-local-model', label: 'Other / custom GGUF model' },
    ],
    requiresKey: false,
    detail:
      'Stable Argentum-managed llama.cpp route. The desktop app controls a localhost llama-server process when the binary and a GGUF model are installed.',
    highlights: [
      'Bundled/local server control layer',
      'OpenAI-compatible /v1 endpoint',
      'Runs only on localhost by default',
    ],
    dataRegion: 'Local machine. No provider receives data unless you point the endpoint elsewhere.',
    dataRoute:
      'Requests go to the Argentum-managed llama.cpp endpoint on 127.0.0.1. Models can live under the selected workspace, be explicitly selected as an external GGUF file, or be downloaded by llama.cpp from a Hugging Face preset.',
    docsUrl: 'https://github.com/ggml-org/llama.cpp/tree/master/tools/server',
    termsUrl: 'https://github.com/ggml-org/llama.cpp/blob/master/LICENSE',
    privacyUrl: 'https://github.com/ggml-org/llama.cpp',
    usageNotes:
      'Usage is local hardware pressure: RAM, VRAM, context size, GPU layers, threads, and model throughput. No API quota exists.',
    modelSearchUrl: 'https://huggingface.co/models?search=gguf',
  },
  {
    id: 'ollama',
    access: 'testing',
    label: 'Ollama / local',
    api: 'openai',
    apiKeyEnv: 'OLLAMA_API_KEY',
    websiteUrl: 'https://ollama.com',
    authMethods: ['api-key'],
    defaultBaseUrl: 'http://127.0.0.1:11434/v1',
    defaultModel: 'llama3.1',
    models: [
      { id: 'llama3.1', label: 'Llama 3.1' },
      { id: 'llama3.2', label: 'Llama 3.2' },
      { id: 'qwen2.5', label: 'Qwen 2.5' },
      { id: 'mistral', label: 'Mistral' },
      { id: 'codellama', label: 'Code Llama' },
    ],
    requiresKey: false,
    detail: 'Ollama or another OpenAI-compatible local server. Usually no API key is needed.',
    highlights: [
      'Local endpoint',
      'No cloud provider by default',
      'Testing route until local server responds',
    ],
    dataRegion: 'Local machine unless your Ollama server is remote.',
    dataRoute: 'Requests go to the configured Ollama-compatible endpoint.',
    docsUrl: 'https://ollama.com/library',
    termsUrl: 'https://ollama.com/terms',
    privacyUrl: 'https://ollama.com/privacy',
    usageNotes: 'Provider account usage is not available for local endpoints.',
    modelSearchUrl: 'https://huggingface.co/models',
  },
  {
    id: 'custom',
    access: 'testing',
    label: 'Custom endpoint',
    api: 'openai',
    apiKeyEnv: 'CUSTOM_API_KEY',
    websiteUrl: 'https://github.com/openai/openai-openapi',
    authMethods: ['api-key'],
    defaultBaseUrl: 'http://127.0.0.1:8000/v1',
    defaultModel: 'custom-model',
    models: [
      { id: 'custom-model', label: 'Custom endpoint default' },
      { id: 'openai-compatible-model', label: 'OpenAI-compatible model' },
      { id: 'local-model', label: 'Local model' },
      { id: 'chat-model', label: 'Generic chat model' },
    ],
    requiresKey: false,
    detail: 'Use your own OpenAI-compatible or Anthropic-compatible endpoint.',
    highlights: [
      'Bring your own endpoint',
      'OpenAI or Anthropic-compatible shape',
      'Testing route until endpoint responds',
    ],
    dataRegion: 'Depends on the custom endpoint you configure.',
    dataRoute: 'Requests go only to the base URL you enter.',
    docsUrl: 'https://github.com/openai/openai-openapi',
    termsUrl: 'https://github.com/openai/openai-openapi',
    privacyUrl: 'https://github.com/openai/openai-openapi',
    usageNotes:
      'Usage is available only when the endpoint returns compatible headers or body fields.',
  },
];

export const providerAuthMethods = [
  {
    id: 'api-key',
    label: 'API key / Platform API',
    status: 'Available',
    detail:
      'Direct live model calls use the provider API with a key stored in the selected workspace secrets file.',
  },
  {
    id: 'browser-account',
    label: 'Browser account authorization',
    status: 'OpenAI/Codex OAuth',
    detail:
      'Use the official Codex device authorization flow. Argentum stores the resulting credentials inside the selected workspace and never scrapes browser sessions.',
  },
];

export const channelOptions = [
  {
    id: 'local',
    label: 'Local app',
    locked: true,
    status: 'Always on',
    detail:
      'The desktop app can work inside the selected workspace folder even when every outside channel is off.',
  },
  {
    id: 'webchat',
    label: 'Webchat',
    status: 'Optional',
    detail: 'Expose a local browser chat after you set an auth token and port.',
  },
  {
    id: 'telegram',
    label: 'Telegram',
    status: 'Optional',
    detail: 'Connect a Telegram bot only for allowed users or chats.',
  },
  {
    id: 'whatsapp',
    label: 'WhatsApp',
    status: 'Advanced',
    detail:
      'Selectable as a channel choice, but full Business API webhook setup may still be required.',
  },
];

export const securityProfiles = [
  {
    id: 'restricted',
    label: 'Restricted workspace',
    detail:
      'Argentum can read and write only inside the selected workspace folder unless you approve more.',
  },
  {
    id: 'ask',
    label: 'Ask every time',
    detail: 'Every shell, network, browser, OS, or external folder action asks before it runs.',
  },
  {
    id: 'session',
    label: 'Session grants',
    detail: 'You can grant a capability for the current session, then it expires.',
  },
  {
    id: 'trusted',
    label: 'Trusted mode',
    detail:
      'Fewer prompts for power users. Still audited, but not recommended as the first profile.',
  },
];

export const commandCatalog = [
  {
    id: 'gateway-start',
    section: 'gateway',
    title: 'Start Gateway',
    command: 'argentum gateway start',
    buttonLabel: 'Start',
    summary: 'Start the local API gateway for the selected workspace.',
    risk: 'Network: local',
  },
  {
    id: 'gateway-status',
    section: 'gateway',
    title: 'Gateway Status',
    command: 'argentum gateway status',
    buttonLabel: 'Check',
    summary: 'Show whether the gateway is stopped or running, including PID and health URL.',
    risk: 'Read-only',
  },
  {
    id: 'gateway-stop',
    section: 'gateway',
    title: 'Stop Gateway',
    command: 'argentum gateway stop',
    buttonLabel: 'Stop',
    summary: 'Stop the gateway process tracked by this workspace.',
    risk: 'Runtime control',
  },
  {
    id: 'gateway-logs',
    section: 'gateway',
    title: 'View Logs',
    command: 'argentum gateway logs -n 100',
    buttonLabel: 'Logs',
    summary: 'Print recent gateway output with sensitive lines redacted.',
    risk: 'Read-only',
  },
  {
    id: 'llama-server-install',
    section: 'local-server',
    title: 'Install llama.cpp',
    command: 'argentum llama-server install',
    buttonLabel: 'Install',
    summary: 'Download and install the vetted llama.cpp server into the selected workspace.',
    risk: 'Network download',
  },
  {
    id: 'llama-server-start',
    section: 'local-server',
    title: 'Start llama.cpp',
    command: 'argentum llama-server start',
    buttonLabel: 'Start',
    summary: 'Start the Argentum-managed llama.cpp server for the selected workspace model.',
    risk: 'Local runtime',
  },
  {
    id: 'llama-server-status',
    section: 'local-server',
    title: 'llama.cpp Status',
    command: 'argentum llama-server status',
    buttonLabel: 'Check',
    summary: 'Check whether the local llama.cpp server binary is installed and running.',
    risk: 'Read-only',
  },
  {
    id: 'llama-server-stop',
    section: 'local-server',
    title: 'Stop llama.cpp',
    command: 'argentum llama-server stop',
    buttonLabel: 'Stop',
    summary: 'Stop the tracked llama.cpp server process for this workspace.',
    risk: 'Runtime control',
  },
  {
    id: 'llama-server-logs',
    section: 'local-server',
    title: 'llama.cpp Logs',
    command: 'argentum llama-server logs -n 100',
    buttonLabel: 'Logs',
    summary: 'Show recent llama.cpp server output with sensitive lines redacted.',
    risk: 'Read-only',
  },
  {
    id: 'doctor',
    section: 'diagnostics',
    title: 'Run doctor',
    command: 'argentum doctor',
    buttonLabel: 'Run',
    summary: 'Check config, data folders, compiled features, and native dependencies.',
    risk: 'Read-only',
  },
  {
    id: 'security-status',
    section: 'security',
    title: 'Security overview',
    command: 'argentum security status',
    buttonLabel: 'Review',
    summary: 'Review policy, sandbox, credentials, approvals, and audit posture.',
    risk: 'Read-only',
  },
  {
    id: 'security-approvals',
    section: 'security',
    title: 'Review approvals',
    command: 'argentum security approvals',
    buttonLabel: 'Review',
    summary: 'Inspect permission requests before granting a scoped capability.',
    risk: 'Approval required',
  },
  {
    id: 'logs-gateway',
    section: 'logs',
    title: 'View gateway logs',
    command: 'argentum gateway logs -n 100',
    buttonLabel: 'Refresh',
    summary: 'Read recent gateway logs from the selected workspace.',
    risk: 'Read-only',
  },
  {
    id: 'settings-config',
    section: 'settings',
    title: 'Show config',
    command: 'argentum config',
    buttonLabel: 'Open',
    summary: 'Open current config values and verify where they are stored.',
    risk: 'Read-only',
  },
  {
    id: 'telegram-status',
    section: 'settings',
    title: 'Telegram status',
    command: 'argentum telegram status',
    buttonLabel: 'Test',
    summary: 'Read the latest Telegram bot diagnostics captured by Argentum.',
    risk: 'Read-only',
  },
];
