export const APP_VERSION = '0.0.4';

export const sections = [
  { id: 'onboarding', icon: 'spark', title: 'Onboarding', eyebrow: 'First run', requiresSetup: false },
  { id: 'chat', icon: 'chat', title: 'Chat', eyebrow: 'Workspace', requiresSetup: false },
  { id: 'agents', icon: 'agent', title: 'Agents', eyebrow: 'Profiles', requiresSetup: true },
  { id: 'runner', icon: 'play', title: 'Agent Runner', eyebrow: 'Execution', requiresSetup: true },
  { id: 'skills', icon: 'blocks', title: 'Skills Library', eyebrow: 'Capabilities', requiresSetup: true },
  { id: 'webchat', icon: 'channel', title: 'Channels', eyebrow: 'Connections', requiresSetup: true },
  { id: 'graph', icon: 'graph', title: 'Knowledge Graph', eyebrow: 'Memory map', requiresSetup: true },
  { id: 'memory', icon: 'memory', title: 'Memory', eyebrow: 'Recall', requiresSetup: true },
  { id: 'logs', icon: 'logs', title: 'Activity Logs', eyebrow: 'Timeline', requiresSetup: true },
  { id: 'security', icon: 'shield', title: 'Security & Permissions', eyebrow: 'Control', requiresSetup: false },
  { id: 'settings', icon: 'settings', title: 'Settings', eyebrow: 'Configuration', requiresSetup: false },
  { id: 'diagnostics', icon: 'pulse', title: 'Diagnostics', eyebrow: 'Doctor', requiresSetup: false },
];

export const onboardingSteps = [
  'Welcome',
  'Workspace location',
  'Runtime mode',
  'Capabilities',
  'AI provider',
  'Channels',
  'Security posture',
  'Review and test',
  'Finish and launch',
];

export const experienceLevels = [
  {
    id: 'beginner',
    label: 'Beginner',
    headline: 'Explain each choice',
    detail: 'Argentum will use plain language, examples, and safer defaults while you set it up.',
  },
  {
    id: 'comfortable',
    label: 'Comfortable',
    headline: 'Balanced guidance',
    detail: 'You get the important tradeoffs without every setting slowing you down.',
  },
  {
    id: 'expert',
    label: 'Expert',
    headline: 'Show the controls',
    detail: 'Argentum keeps the explanations compact and puts advanced options closer to the surface.',
  },
];

export const runtimeModes = [
  {
    id: 'desktop',
    label: 'Desktop app',
    headline: 'GUI first, CLI included',
    detail: 'Best for Windows users. You get onboarding, chat, settings, approvals, logs, and diagnostics in the app.',
    preview: 'A native desktop workspace opens after setup. Terminal tools remain available for automation.',
  },
  {
    id: 'cli',
    label: 'CLI tools',
    headline: 'Terminal-first workflow',
    detail: 'Best for Linux users, scripts, and people who prefer command-line control.',
    preview: 'The app keeps the same setup values, but daily work happens through argentum commands.',
  },
  {
    id: 'service',
    label: 'Local service',
    headline: 'Service with desktop control',
    detail: 'Best when Argentum should expose local APIs, webchat, or integrations after approval.',
    preview: 'Services stay off until you approve them. The desktop app acts as the control room.',
  },
];

export const providerPresets = [
  {
    id: 'openai',
    label: 'OpenAI',
    api: 'openai',
    apiKeyEnv: 'OPENAI_API_KEY',
    defaultBaseUrl: 'https://api.openai.com/v1',
    defaultModel: 'gpt-4o-mini',
    requiresKey: true,
    detail: 'General hosted models with strong tool and chat support.',
  },
  {
    id: 'anthropic',
    label: 'Anthropic Claude',
    api: 'anthropic',
    apiKeyEnv: 'ANTHROPIC_API_KEY',
    defaultBaseUrl: 'https://api.anthropic.com',
    defaultModel: 'claude-sonnet-4-20250514',
    requiresKey: true,
    detail: 'Hosted Claude models. Good for long, careful reasoning.',
  },
  {
    id: 'google',
    label: 'Google Gemini',
    api: 'openai',
    apiKeyEnv: 'GOOGLE_API_KEY',
    defaultBaseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai/',
    defaultModel: 'gemini-2.5-flash',
    requiresKey: true,
    detail: 'Gemini through the OpenAI-compatible endpoint.',
  },
  {
    id: 'openrouter',
    label: 'OpenRouter',
    api: 'openai',
    apiKeyEnv: 'OPENROUTER_API_KEY',
    defaultBaseUrl: 'https://openrouter.ai/api/v1',
    defaultModel: 'google/gemma-3-27b-it',
    requiresKey: true,
    detail: 'One endpoint for many hosted model providers.',
  },
  {
    id: 'nvidia',
    label: 'NVIDIA',
    api: 'openai',
    apiKeyEnv: 'NVIDIA_API_KEY',
    defaultBaseUrl: 'https://integrate.api.nvidia.com/v1',
    defaultModel: 'deepseek-ai/deepseek-v3.2',
    requiresKey: true,
    detail: 'NVIDIA-hosted OpenAI-compatible models.',
  },
  {
    id: 'groq',
    label: 'Groq',
    api: 'openai',
    apiKeyEnv: 'GROQ_API_KEY',
    defaultBaseUrl: 'https://api.groq.com/openai/v1',
    defaultModel: 'meta-llama/llama-4-scout-17b-16e-instruct',
    requiresKey: true,
    detail: 'Fast hosted OpenAI-compatible inference.',
  },
  {
    id: 'minimax',
    label: 'MiniMax',
    api: 'openai',
    apiKeyEnv: 'MINIMAX_API_KEY',
    defaultBaseUrl: 'https://api.minimax.io/v1',
    defaultModel: 'MiniMax-M2.7',
    requiresKey: true,
    detail: 'MiniMax hosted models through an OpenAI-style API.',
  },
  {
    id: 'ollama',
    label: 'Ollama / local',
    api: 'openai',
    apiKeyEnv: 'OLLAMA_API_KEY',
    defaultBaseUrl: 'http://127.0.0.1:11434/v1',
    defaultModel: 'llama3.1',
    requiresKey: false,
    detail: 'Local models on your machine. Usually no API key is needed.',
  },
  {
    id: 'custom',
    label: 'Custom endpoint',
    api: 'openai',
    apiKeyEnv: 'CUSTOM_API_KEY',
    defaultBaseUrl: 'http://127.0.0.1:8000/v1',
    defaultModel: 'custom-model',
    requiresKey: false,
    detail: 'Use your own OpenAI-compatible or Anthropic-compatible endpoint.',
  },
];

export const channelOptions = [
  {
    id: 'local',
    label: 'Local app',
    locked: true,
    status: 'Always on',
    detail: 'The desktop app can work inside the selected workspace folder even when every outside channel is off.',
  },
  {
    id: 'webchat',
    label: 'Webchat',
    status: 'Optional',
    detail: 'Expose a local browser chat after you set an auth token and port.',
  },
  {
    id: 'telegram',
    label: 'Telegram',
    status: 'Optional',
    detail: 'Connect a Telegram bot only for allowed users or chats.',
  },
  {
    id: 'whatsapp',
    label: 'WhatsApp',
    status: 'Advanced',
    detail: 'Prepared as a channel choice, but full Business API webhook setup may still be required.',
  },
];

export const securityProfiles = [
  {
    id: 'restricted',
    label: 'Restricted workspace',
    detail: 'Argentum can read and write only inside the selected workspace folder unless you approve more.',
  },
  {
    id: 'ask',
    label: 'Ask every time',
    detail: 'Every shell, network, browser, OS, or external folder action asks before it runs.',
  },
  {
    id: 'session',
    label: 'Session grants',
    detail: 'You can grant a capability for the current session, then it expires.',
  },
  {
    id: 'trusted',
    label: 'Trusted mode',
    detail: 'Fewer prompts for power users. Still audited, but not recommended as the first profile.',
  },
];

export const commandCatalog = [
  {
    id: 'chat-start',
    section: 'chat',
    title: 'Start local gateway',
    command: 'argentum gateway start',
    summary: 'Bring the local API and web gateway online after permissions are reviewed.',
    risk: 'Network: local',
  },
  {
    id: 'gateway-status',
    section: 'chat',
    title: 'Check gateway status',
    command: 'argentum gateway status',
    summary: 'Confirm whether the local gateway is running and which port it owns.',
    risk: 'Read-only',
  },
  {
    id: 'doctor',
    section: 'diagnostics',
    title: 'Run doctor',
    command: 'argentum doctor',
    summary: 'Check config, data folders, compiled features, and native dependencies.',
    risk: 'Read-only',
  },
  {
    id: 'security-status',
    section: 'security',
    title: 'Security overview',
    command: 'argentum security status',
    summary: 'Review policy, sandbox, credentials, approvals, and audit posture.',
    risk: 'Read-only',
  },
  {
    id: 'security-approvals',
    section: 'security',
    title: 'Review approvals',
    command: 'argentum security approvals',
    summary: 'Inspect permission requests before granting a scoped capability.',
    risk: 'Approval required',
  },
  {
    id: 'agents-list',
    section: 'agents',
    title: 'List agents',
    command: 'argentum agents list',
    summary: 'Show configured agent profiles, model routing, and workspace scope.',
    risk: 'Read-only',
  },
  {
    id: 'runner-acp',
    section: 'runner',
    title: 'Run sandbox task',
    command: 'argentum acp run "code"',
    summary: 'Execute approved code through the sandbox runner.',
    risk: 'Approval required',
  },
  {
    id: 'skills-list',
    section: 'skills',
    title: 'List installed skills',
    command: 'argentum skill list',
    summary: 'Audit installed skills and their workspace-visible capabilities.',
    risk: 'Read-only',
  },
  {
    id: 'webchat-config',
    section: 'webchat',
    title: 'Show channel config',
    command: 'argentum config channels',
    summary: 'Review local app, webchat, Telegram, and WhatsApp channel settings.',
    risk: 'Read-only',
  },
  {
    id: 'graph-feature',
    section: 'graph',
    title: 'Inspect graph feature',
    command: 'argentum feature knowledge-graph',
    summary: 'View feature health, configuration, and entry points for graph memory.',
    risk: 'Read-only',
  },
  {
    id: 'memory-search',
    section: 'memory',
    title: 'Search memory',
    command: 'argentum memory search "project context"',
    summary: 'Search workspace memory without granting access outside Argentum.',
    risk: 'Read-only',
  },
  {
    id: 'logs-gateway',
    section: 'logs',
    title: 'View gateway logs',
    command: 'argentum gateway logs --lines 100',
    summary: 'Read recent gateway logs from the selected workspace.',
    risk: 'Read-only',
  },
  {
    id: 'settings-config',
    section: 'settings',
    title: 'Show config',
    command: 'argentum config',
    summary: 'Open current config values and verify where they are stored.',
    risk: 'Read-only',
  },
];
