export const APP_VERSION = '0.0.4';

export const sections = [
  { id: 'onboarding', icon: 'spark', title: 'Onboarding', eyebrow: 'First run', requiresSetup: false },
  { id: 'chat', icon: 'chat', title: 'Chat', eyebrow: 'Workspace', requiresSetup: false },
  { id: 'gateway', icon: 'gateway', title: 'Gateway', eyebrow: 'Runtime', requiresSetup: true },
  { id: 'security', icon: 'shield', title: 'Security & Permissions', eyebrow: 'Control', requiresSetup: false },
  { id: 'settings', icon: 'settings', title: 'Settings', eyebrow: 'Configuration', requiresSetup: false },
  { id: 'diagnostics', icon: 'pulse', title: 'Diagnostics', eyebrow: 'Doctor', requiresSetup: false },
  { id: 'logs', icon: 'logs', title: 'Activity Logs', eyebrow: 'Timeline', requiresSetup: true },
];

export const onboardingSteps = [
  'Welcome',
  'Workspace location',
  'Runtime mode',
  'Capabilities',
  'AI provider',
  'Channels',
  'Security posture',
  'Review > Test > Pass',
];

export const experienceLevels = [
  {
    id: 'beginner',
    label: 'Beginner',
    headline: 'Explain each choice',
    detail: 'Argentum will use plain language, examples, and safer defaults while you set it up.',
  },
  {
    id: 'comfortable',
    label: 'Comfortable',
    headline: 'Balanced guidance',
    detail: 'You get the important tradeoffs without every setting slowing you down.',
  },
  {
    id: 'expert',
    label: 'Expert',
    headline: 'Show the controls',
    detail: 'Argentum keeps the explanations compact and puts advanced options closer to the surface.',
  },
];

export const runtimeModes = [
  {
    id: 'desktop',
    label: 'Desktop app',
    headline: 'GUI first, CLI included',
    detail: 'Best for Windows users. You get onboarding, chat, settings, approvals, logs, and diagnostics in the app.',
    preview: 'A native desktop workspace opens after setup. Terminal tools remain available for automation.',
    examples: [
      'Ask Argentum to read a workspace file.',
      'Approve the scoped file request.',
      'See the result, audit note, and next action in Chat.',
    ],
    demoSteps: ['Chat request', 'Permission card', 'Workspace answer'],
  },
  {
    id: 'cli',
    label: 'CLI tools',
    headline: 'Terminal-first workflow',
    detail: 'Best for Linux users, scripts, and people who prefer command-line control.',
    preview: 'The app keeps the same setup values, but daily work happens through argentum commands.',
    examples: [
      'Run argentum doctor to verify config.',
      'Use argentum gateway status before exposing a channel.',
      'Keep scripted work visible in logs.',
    ],
    demoSteps: ['Command', 'Check', 'Log'],
  },
  {
    id: 'service',
    label: 'Local service',
    headline: 'Service with desktop control',
    detail: 'Best when Argentum should expose local APIs, webchat, or integrations after approval.',
    preview: 'Services stay off until you approve them. The desktop app acts as the control room.',
    examples: [
      'Start the gateway from Chat.',
      'Approve the local network capability.',
      'Watch the service status in the terminal view.',
    ],
    demoSteps: ['Start', 'Approve', 'Serve'],
  },
];

export const providerPresets = [
  {
    id: 'openai',
    label: 'OpenAI',
    api: 'openai',
    apiKeyEnv: 'OPENAI_API_KEY',
    defaultBaseUrl: 'https://api.openai.com/v1',
    defaultModel: 'gpt-4o-mini',
    models: [
      { id: 'gpt-4o-mini', label: 'GPT-4o mini' },
      { id: 'gpt-4o', label: 'GPT-4o' },
      { id: 'gpt-4.1-mini', label: 'GPT-4.1 mini' },
      { id: 'gpt-4.1', label: 'GPT-4.1' },
      { id: 'o4-mini', label: 'o4-mini' },
    ],
    requiresKey: true,
    detail: 'General hosted models with strong tool and chat support.',
  },
  {
    id: 'anthropic',
    label: 'Anthropic Claude',
    api: 'anthropic',
    apiKeyEnv: 'ANTHROPIC_API_KEY',
    defaultBaseUrl: 'https://api.anthropic.com',
    defaultModel: 'claude-sonnet-4-20250514',
    models: [
      { id: 'claude-sonnet-4-20250514', label: 'Claude Sonnet 4' },
      { id: 'claude-opus-4-20250514', label: 'Claude Opus 4' },
      { id: 'claude-3-5-haiku-20241022', label: 'Claude 3.5 Haiku' },
    ],
    requiresKey: true,
    detail: 'Hosted Claude models. Good for long, careful reasoning.',
  },
  {
    id: 'google',
    label: 'Google Gemini',
    api: 'openai',
    apiKeyEnv: 'GOOGLE_API_KEY',
    defaultBaseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai/',
    defaultModel: 'gemini-2.5-flash',
    models: [
      { id: 'gemini-2.5-flash', label: 'Gemini 2.5 Flash' },
      { id: 'gemini-2.5-pro', label: 'Gemini 2.5 Pro' },
      { id: 'gemini-2.0-flash', label: 'Gemini 2.0 Flash' },
    ],
    requiresKey: true,
    detail: 'Gemini through the OpenAI-compatible endpoint.',
  },
  {
    id: 'openrouter',
    label: 'OpenRouter',
    api: 'openai',
    apiKeyEnv: 'OPENROUTER_API_KEY',
    defaultBaseUrl: 'https://openrouter.ai/api/v1',
    defaultModel: 'google/gemma-3-27b-it',
    models: [
      { id: 'google/gemma-3-27b-it', label: 'Google Gemma 3 27B' },
      { id: 'openai/gpt-4o-mini', label: 'OpenAI GPT-4o mini' },
      { id: 'anthropic/claude-sonnet-4', label: 'Anthropic Claude Sonnet 4' },
      { id: 'google/gemini-2.5-flash', label: 'Google Gemini 2.5 Flash' },
      { id: 'meta-llama/llama-3.3-70b-instruct', label: 'Llama 3.3 70B Instruct' },
    ],
    requiresKey: true,
    detail: 'One endpoint for many hosted model providers.',
  },
  {
    id: 'nvidia',
    label: 'NVIDIA',
    api: 'openai',
    apiKeyEnv: 'NVIDIA_API_KEY',
    defaultBaseUrl: 'https://integrate.api.nvidia.com/v1',
    defaultModel: 'deepseek-ai/deepseek-v3.2',
    models: [
      { id: 'deepseek-ai/deepseek-v3.2', label: 'DeepSeek V3.2' },
      { id: 'nvidia/llama-3.1-nemotron-70b-instruct', label: 'Llama 3.1 Nemotron 70B' },
      { id: 'meta/llama-3.1-405b-instruct', label: 'Llama 3.1 405B' },
    ],
    requiresKey: true,
    detail: 'NVIDIA-hosted OpenAI-compatible models.',
  },
  {
    id: 'groq',
    label: 'Groq',
    api: 'openai',
    apiKeyEnv: 'GROQ_API_KEY',
    defaultBaseUrl: 'https://api.groq.com/openai/v1',
    defaultModel: 'meta-llama/llama-4-scout-17b-16e-instruct',
    models: [
      { id: 'meta-llama/llama-4-scout-17b-16e-instruct', label: 'Llama 4 Scout' },
      { id: 'llama-3.3-70b-versatile', label: 'Llama 3.3 70B Versatile' },
      { id: 'openai/gpt-oss-120b', label: 'GPT OSS 120B' },
      { id: 'openai/gpt-oss-20b', label: 'GPT OSS 20B' },
    ],
    requiresKey: true,
    detail: 'Fast hosted OpenAI-compatible inference.',
  },
  {
    id: 'minimax',
    label: 'MiniMax',
    api: 'openai',
    apiKeyEnv: 'MINIMAX_API_KEY',
    defaultBaseUrl: 'https://api.minimax.io/v1',
    defaultModel: 'MiniMax-M2.7',
    models: [
      { id: 'MiniMax-M2.7', label: 'MiniMax M2.7' },
      { id: 'MiniMax-Text-01', label: 'MiniMax Text 01' },
    ],
    requiresKey: true,
    detail: 'MiniMax hosted models through an OpenAI-style API.',
  },
  {
    id: 'ollama',
    label: 'Ollama / local',
    api: 'openai',
    apiKeyEnv: 'OLLAMA_API_KEY',
    defaultBaseUrl: 'http://127.0.0.1:11434/v1',
    defaultModel: 'llama3.1',
    models: [
      { id: 'llama3.1', label: 'Llama 3.1' },
      { id: 'llama3.2', label: 'Llama 3.2' },
      { id: 'qwen2.5', label: 'Qwen 2.5' },
      { id: 'mistral', label: 'Mistral' },
      { id: 'codellama', label: 'Code Llama' },
    ],
    requiresKey: false,
    detail: 'Local models on your machine. Usually no API key is needed.',
  },
  {
    id: 'custom',
    label: 'Custom endpoint',
    api: 'openai',
    apiKeyEnv: 'CUSTOM_API_KEY',
    defaultBaseUrl: 'http://127.0.0.1:8000/v1',
    defaultModel: 'custom-model',
    models: [
      { id: 'custom-model', label: 'Custom endpoint default' },
      { id: 'openai-compatible-model', label: 'OpenAI-compatible model' },
      { id: 'local-model', label: 'Local model' },
      { id: 'chat-model', label: 'Generic chat model' },
    ],
    requiresKey: false,
    detail: 'Use your own OpenAI-compatible or Anthropic-compatible endpoint.',
  },
];

export const channelOptions = [
  {
    id: 'local',
    label: 'Local app',
    locked: true,
    status: 'Always on',
    detail: 'The desktop app can work inside the selected workspace folder even when every outside channel is off.',
  },
  {
    id: 'webchat',
    label: 'Webchat',
    status: 'Optional',
    detail: 'Expose a local browser chat after you set an auth token and port.',
  },
  {
    id: 'telegram',
    label: 'Telegram',
    status: 'Optional',
    detail: 'Connect a Telegram bot only for allowed users or chats.',
  },
  {
    id: 'whatsapp',
    label: 'WhatsApp',
    status: 'Advanced',
    detail: 'Selectable as a channel choice, but full Business API webhook setup may still be required.',
  },
];

export const securityProfiles = [
  {
    id: 'restricted',
    label: 'Restricted workspace',
    detail: 'Argentum can read and write only inside the selected workspace folder unless you approve more.',
  },
  {
    id: 'ask',
    label: 'Ask every time',
    detail: 'Every shell, network, browser, OS, or external folder action asks before it runs.',
  },
  {
    id: 'session',
    label: 'Session grants',
    detail: 'You can grant a capability for the current session, then it expires.',
  },
  {
    id: 'trusted',
    label: 'Trusted mode',
    detail: 'Fewer prompts for power users. Still audited, but not recommended as the first profile.',
  },
];

export const commandCatalog = [
  {
    id: 'gateway-start',
    section: 'gateway',
    title: 'Start Gateway',
    command: 'argentum gateway start',
    buttonLabel: 'Start',
    summary: 'Start the local API gateway for the selected workspace.',
    risk: 'Network: local',
  },
  {
    id: 'gateway-status',
    section: 'gateway',
    title: 'Gateway Status',
    command: 'argentum gateway status',
    buttonLabel: 'Check',
    summary: 'Show whether the gateway is stopped or running, including PID and health URL.',
    risk: 'Read-only',
  },
  {
    id: 'gateway-stop',
    section: 'gateway',
    title: 'Stop Gateway',
    command: 'argentum gateway stop',
    buttonLabel: 'Stop',
    summary: 'Stop the gateway process tracked by this workspace.',
    risk: 'Runtime control',
  },
  {
    id: 'gateway-logs',
    section: 'gateway',
    title: 'View Logs',
    command: 'argentum gateway logs -n 100',
    buttonLabel: 'Logs',
    summary: 'Print recent gateway output with sensitive lines redacted.',
    risk: 'Read-only',
  },
  {
    id: 'doctor',
    section: 'diagnostics',
    title: 'Run doctor',
    command: 'argentum doctor',
    buttonLabel: 'Run',
    summary: 'Check config, data folders, compiled features, and native dependencies.',
    risk: 'Read-only',
  },
  {
    id: 'security-status',
    section: 'security',
    title: 'Security overview',
    command: 'argentum security status',
    buttonLabel: 'Review',
    summary: 'Review policy, sandbox, credentials, approvals, and audit posture.',
    risk: 'Read-only',
  },
  {
    id: 'security-approvals',
    section: 'security',
    title: 'Review approvals',
    command: 'argentum security approvals',
    buttonLabel: 'Review',
    summary: 'Inspect permission requests before granting a scoped capability.',
    risk: 'Approval required',
  },
  {
    id: 'logs-gateway',
    section: 'logs',
    title: 'View gateway logs',
    command: 'argentum gateway logs -n 100',
    buttonLabel: 'Refresh',
    summary: 'Read recent gateway logs from the selected workspace.',
    risk: 'Read-only',
  },
  {
    id: 'settings-config',
    section: 'settings',
    title: 'Show config',
    command: 'argentum config',
    buttonLabel: 'Open',
    summary: 'Open current config values and verify where they are stored.',
    risk: 'Read-only',
  },
];
